config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "vehicles", to: "vehicles#home"
  # get "vehicles/index", to: "vehicles#index"

  resources :vehicles do
    resources :bookings, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :location, :date_start, :date_finish, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :bookings
  has_many :users, through: :bookings

  validates :title, :category, :description, :precio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    # we need @list in our `simple_form_for`
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking.vehicle = @vehicle
    if @booking.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to vehicle_path(@booking.vehicle)
  end


  private

  def booking_params
    # params.require(:booking).permit(:comment)
    params.require(:booking).permit(:location, :date_start, :date_finish, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
    # no need for app/views/restaurants/create.html.erb
    # redirect_to restaurant_path(@restaurant)
  end

  # def edit
  #   @vehicle = Vehicle.find(params[:id])
  # end

  # def update
  #   @vehicle = Vehicle.find(params[:id])
  #   @vehicle.update(task_params)

  #   # no need for app/views/vehicle/update.html.erb
  #   redirect_to vehicle_index_path(@vehicle)
  #   # Will raise ActiveModel::ForbiddenAttributesError
  # end

  private

  def vehicle_params
    params.require(:vehicle).permit(:title, :category, :precio, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for [ @vehicle, @booking ] do |f| %>
  <%= f.input :ciudad %>
  <%= f.input :date_start %>
  <%= f.input :date_finish %>
  <%= f.submit "Save ", class: "btn btn-primary" %>
<% end %>
<a href="/vehicles">Home</a>
<div class="container pt-5">
  <h1>Reserve</h1>
  <%= simple_form_for(@vehicle) do |f| %>
    <%= f.input :location, collection: ["Lima", "La Libertad", "Ica", "Cusco"] %>
    <%= f.input :date_start %>
    <%= f.input :date_finish %>
    <%= f.input :description %>
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  <% end %>
</div>
<a href="/vehicles/index">Back to list</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoCeroConDevise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenido</h1>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1513113703321-437d5f417ac7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=964&q=80);">
  <div class="container">
    <h1>Que <strong>no</strong> te <strong>lo cuenten</strong>!</h1>
    <p>Ven y descúbrelo tú mismo</p>
    <a class="btn btn-primary" href="#">Apply now</a>
  </div>
</div>

<div class="container">
  <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1441148345475-03a2e82f9719?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
    Autos
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
    Bicicletas
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1605798410801-e7680bf2cdc8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
    Scooters
  </div>
  </div>
  <div class="card">
    <a class="btn btn-primary" href="/vehicles">See more</a>
  </div>

</div>





<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Euphoria Land
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vehicles/edit.html.erb
<%= form_for(@vehicle) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :precio%>
  <%= f.text_field :precio%>
  <%= f.submit %>
<% end %>

<%= link_to("Back to list", vehicles_index_path) %>

app/views/vehicles/index.html.erb
<h1 class="title-index" style="text-align: center; font-family: cursive;">My vehicles</h1>
<div class="container">


  <%# <div class="d-flex justify-content-around"> %>
  <div class="row justify-content-around">

  <% @vehicles.each do |vehicle|%>
    <div class="card-group" style="margin-bottom: 20px;">


      <div class="card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1563460937-8e3fd7f161f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= vehicle.title %></h5>
          <p class="card-text"><%= vehicle.precio %></p>
          <%# <%= link to "go somewhere", vehicle_path(vehicle), class:"btn btn-primary" %>
          <a class = "btn btn-primary" href="/vehicles/:id"> Ver más </a>
        </div>
      </div>
    </div>


  <% end %>
  <%# <a href="/vehicles/new"> + Add a new vehicle </a> %>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container">
<div class="row">
<div class="col"><br><br><br><br><br><br></div></div>
</div>
<div class="container">
  <h1>Add a new vehicle</h1>
  <%= simple_form_for(@vehicle) do |f| %>
    <%= f.input :title %>
    <%= f.input :category, collection: ["Auto", "Bicicleta", "Scooter"] %>
    <%= f.input :precio %>
    <%= f.input :description %>
    <%= f.submit "Guardar", class: "btn btn-success" %>
  <% end %>
</div>
<a href="/vehicles/index">Back to list</a>

app/views/vehicles/show.html.erb
<h1><%= @vehicle.title %></h1>
<div><h2><%= @vehicle.category %></h2></div>
<h2><%= @vehicle.description%></h2>
<h3></h3>
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>

      <h1><%= @vehicle.title %></h1>
      <h2><%= @vehicle.category %></h2>
      <p><%= @vehicle.description %></p>

    </div>
    <h2 class="card-trip-pricing">£ <%= @vehicle.precio %></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
<ul>
<li><%= link_to("Edit the list", edit_vehicle_path) %></li>
<li><%= link_to "Borrar", vehicle_path(@vehicle), method: :delete,
     data: {confirm: "Estás seguro?"} %></li>
<li><%= link_to("Back to vehicles", vehicles_index_path) %></li>
</ul>